package voice;


import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;


public class emailFrame extends javax.swing.JFrame {

    String emails[][] = null;

    /**
     * Creates new form emailFrame
     */
    public emailFrame() throws MessagingException, IOException {
        initComponents();
        int start = 0;
        int end = 5;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        jTable1.setModel(model);
        //jTable1.setEnabled(false);
        /*for(int i=0;i<100;i++){
         model.addRow(new Object[] { "row "+i,"row "+i,"row "+i,"row "+i});
         }*/
        /*ArrayList<String[]> emails = getEmails.getAllEmails();
         System.out.println(emails.size());
         for(int i=0;i<emails.size();i++) {
         String[] options = emails.get(i);
         System.out.println(options[0]+options[1]+options[2]+options[3]);
         System.out.println(i);
         model.addRow(new Object[] { options[0],options[1],options[2],options[3] });
         }*/
        emails = getEmails.getAllEmails(start,end);
        for (int i = 0; i < emails.length; i++) {
            model.addRow(new Object[]{emails[i][0], emails[i][1], emails[i][2], emails[i][3]});
        }

        jTable1.addMouseListener(new MouseAdapter() {
            private String[] email;
            public void mouseClicked(MouseEvent e) {
         
               if (e.getClickCount() == 2) {
                    if (jTable1.getSelectedRow() > -1) {
                        // print first column value from selected row
                        // System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                        int selected_email = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                        try {
                            email = getEmails.getSingleEmail(selected_email-1);
                            new singleEmail(email[1], email[2], email[3], email[4]).setVisible(true);
                        } catch (MessagingException ex) {
                            Logger.getLogger(emailFrame.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(emailFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        });

        /* jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (jTable1.getSelectedRow() > -1) {
                    // print first column value from selected row
                    System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                }
            }
        });*/



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No", "From", "Subject", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new emailFrame().setVisible(true);
                } catch (MessagingException ex) {
                    Logger.getLogger(emailFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(emailFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
